module_name: Banner Block
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - advertising
  - banner
  - images
  - gdpr
description_short: The banner block allows you add a banner to the top of your site for advertising purposes.
description: description.md
images:
  - image-1.png
gdpr_compliant: true  
license: MIT
